selected_scheme scheme-minimal
collection-basic 1
collection-langgerman 1
collection-latexextra 1
collection-mathscience 1
collection-luatex 1
tlpdbopt_autobackup 0
tlpdbopt_install_docfiles 0
tlpdbopt_install_srcfiles 0
